; PlatformIO Project Configuration File
; Project: He thong nhung IoT do do gian cua dat
; Hardware: ESP32 + RA-02 LoRa + MPU6050 + capacitive soil moisture sensor

[platformio]
default_envs = gateway

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -I src/common
lib_deps =
    sandeepmistry/LoRa@^0.8.0
    knolleary/PubSubClient@^2.8

[env:node]
build_src_filter =
    -<*>
    +<common/>
    +<node/>

[env:gateway]
build_src_filter =
    -<*>
    +<common/>
    +<gateway/>

